project:
  type: website
  output-dir: docs

website:
  title: "Mathew Frame"
  site-url: https://mathewframe.github.io
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

