---
title: "About"
---

Mathew is a fourth-year finance student at the University of Alberta with a proven track record of exceeding expectations both personally and professionally. In his role at SGI, he found a way to automate over 100 annual hours spent on reporting data. Within 2 months Mathew was tasked with leading and training his team of 9 employees through a major software transition. In his first two weeks at CNRL, Mathew learned how to read engineering drawings from all disciplines and completed analysis of a project worth over \$5 million. By the end of his work term, he was collaborating with engineers to sharpen estimates on a project worth over \$50 million.

Systems and Strategy are two pillars of Mathew’s professional philosophy:

When Mathew was 10 years old, he built automated systems in *Minecraft* to collect resources while he slept. This has translated to his focus on data science and machine learning, to build systems that have real impact, like the data scraper he built at SGI. Beyond digital systems, Mathew is also driven by physical systems like farming, which reflects his long term goal of owning land to raise chickens and to maintain a productive garden.

Mathew gained a passion for trading and strategy during the COVID Lockdown. As a high school student with too much time on his hands, he mastered the auction market of Madden 21, and built a team worth over \$150. This taught him that markets are irrational, and with patience and market knowledge, you can find patterns in irrationality, and turn them into a profit.
